PXS-586 Test implemented blocks
pindex/android pull request #19
Opened 2021-02-19 12:50 UTC by qtipee

- Refactor the Pindex blocks, which are now `Fragments` and each has a related XML file ; the code is much more cleaner and consistent
- Add an instrumented test (UI test) for each Pindex block, asserting that the fragment is displayed (and that the textual content is visible when there is some)
- Add an instrumented test for the `Experience Activity` that tests multiple cases
- Add a unit test for each Pindex block: a test just checks that the fragment is correctly created ; I do not know if it's useful as we're testing the blocks in the instrumented tests, but it might be for some cases

2021-02-20 12:14 UTC, xavierpantet commented
Remove unused converter (in `com/pindex/main/utils/Converter.kt`)

2021-02-20 12:16 UTC, xavierpantet commented
`MediaLoader` has unused imports:

```kotlin
import android.content.Context
import android.util.Log
```

2021-02-20 12:26 UTC, xavierpantet commented
Remove unused decorator (in com/pindex/main/decorators/MarginItemDecorator.kt)

2021-02-20 13:27 UTC, xavierpantet commented
Can we use a faker instead of hardcoding text in the tests? I found [this](https://github.com/blocoio/faker), which looks nice!

2021-02-20 13:35 UTC, xavierpantet requested changes

2021-02-20 13:35 UTC, xavierpantet commented on app/src/androidTest/java/com/pindex/main/home/ExperienceActivityInstrumentedTest.kt
> +        val block = BlockDto(audio = audioBlock, sectionTitle = sectionTitle, type = "audio")
Magic `String`. Can we have that in the resources or as class constant instead?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/androidTest/java/com/pindex/main/home/ExperienceActivityInstrumentedTest.kt
> +        val block = BlockDto(text = textBlock, type = "bigHeader")
Magic `String`. Can we have that in the resources or as class constant instead?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/androidTest/java/com/pindex/main/home/ExperienceActivityInstrumentedTest.kt
> +        val block = BlockDto(image = imageBlock, sectionTitle = sectionTitle, type = "borderlessImage")
Magic `String`. Can we have that in the resources or as class constant instead?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/androidTest/java/com/pindex/main/home/ExperienceActivityInstrumentedTest.kt
> +        val block = BlockDto(text = textBlock, sectionTitle = sectionTitle, type = "text")
Magic `String`. Can we have that in the resources or as class constant instead?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/AudioBlockFragment.kt
> +        val imagePath = arguments?.getString("imagePath")
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/AudioBlockFragment.kt
> +        val audioName = arguments?.getString("name")
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/AudioBlockFragment.kt
> +                    setDataSource(arguments?.getString("audioPath"))
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/BigHeaderBlockFragment.kt
> +        textView.text = arguments?.getString("title")
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/BorderlessImageBlockFragment.kt
> +        val imagePath = arguments?.getString("imagePath")
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/SectionTitleBlockFragment.kt
> +        textView.text = arguments?.getString("title")
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-20 13:35 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/ui/fragments/blocks/TextBlockFragment.kt
> +        textView.text = arguments?.getString("text")
I find this super dangerous... If the key changes in Firebase, it will all break down...

Is there a more "type-safe" alternative or can we use string resources or class constants instead to at least make this more maintainable?

2021-02-22 11:19 UTC, qtipee commented
> Can we use a faker instead of hardcoding text in the tests? I found [this](https://github.com/blocoio/faker), which looks nice!

I found [this one](https://github.com/serpro69/kotlin-faker), which is written fully in Kotlin.

2021-02-22 12:14 UTC, xavierpantet requested changes

2021-02-22 12:14 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/home/ExperienceActivity.kt
>              "audio" -> {
Magic `String`. Can we have that as a constant as well (like for the block fragment arguments)?

2021-02-22 12:14 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/home/ExperienceActivity.kt
>              "bigHeader" -> {
Magic `String`. Can we have that as a constant as well (like for the block fragment arguments)?

2021-02-22 12:14 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/home/ExperienceActivity.kt
>              "borderlessImage" -> {
Magic `String`. Can we have that as a constant as well (like for the block fragment arguments)?

2021-02-22 12:14 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/home/ExperienceActivity.kt
>              "text" -> {
Magic `String`. Can we have that as a constant as well (like for the block fragment arguments)?

2021-02-22 13:18 UTC, xavierpantet approved these changes

2021-02-22 13:18 UTC, merged