PXS-587 Implement Hilt & Mock Test Firestore
pindex/android pull request #21
Opened 2021-02-26 11:26 UTC by qtipee

- Implement Hilt in order to do dependency injection
- Add the MockFirebaseExperienceRepository

2021-03-01 07:20 UTC, xavierpantet commented
@timotheeduran please review this as well!

You should probably have a look [here](https://pindex.atlassian.net/wiki/spaces/PI/pages/711327745/Dependency+Injection).

2021-03-01 10:30 UTC, xavierpantet requested changes

2021-03-01 10:30 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/home/ExperienceActivity.kt
> +//@AndroidEntryPoint
Remove comment

2021-03-01 10:30 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/home/HomeActivity.kt
>          PindexFirebase.signInAnonymously(this)
Is it possible to sign in to Firebase only when we instantiate the repository?

Maybe in `ExperienceRepositoryDI`?

2021-03-01 10:30 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/repositories/FirebaseMockExperienceRepository.kt
> +        for (i in 1..limit) {
I think we can be more concise:

```kotlin
return Array(limit, { _ -> createRandomExperience() }).toCollection(ArrayList())
```

2021-03-01 10:30 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/repositories/FirebaseMockExperienceRepository.kt
> +        val content = ContentDto(
Same comment here on conciseness

2021-03-01 10:30 UTC, xavierpantet commented on app/src/main/java/com/pindex/main/services/ExperienceService.kt
> +    class ExperienceService @Inject constructor (
Remove comment

2021-03-01 11:22 UTC, qtipee commented on app/src/main/java/com/pindex/main/home/HomeActivity.kt
>          PindexFirebase.signInAnonymously(this)
I moved the code that logs the user in inside the `FirebaseExperienceRepository` and it seems to work!

2021-03-01 12:00 UTC, xavierpantet commented
Looks good to me! GG @qtipee!

2021-03-02 14:20 UTC, timotheeduran approved these changes

2021-03-02 14:21 UTC, xavierpantet approved these changes

2021-03-05 07:14 UTC, merged