Feature/182 ar help
pindex/android pull request #218
Opened 2021-05-03 00:22 UTC by Mortadha-abderrhim

Do not review yet

2021-05-05 14:18 UTC, lucasrlt requested changes
The PR is really nice but I made a few comments about code formatting and naming

2021-05-05 14:18 UTC, lucasrlt commented on app/src/androidTest/java/com/pindex/main/ui/activities/AugmentedRealityActivityInstrumentedTest.kt
> +    fun arHelpButtonIsDisplayed(){
You should run the linter on that file to add more spaces between tests

2021-05-05 14:18 UTC, lucasrlt commented on app/src/main/java/com/pindex/main/ui/activities/ARHelpActivity.kt
> +class ARHelpActivity:AppCompatActivity() {
A linter run here would be really helpful here too. + you could add some documentation to explain what this activity does

2021-05-05 14:18 UTC, lucasrlt commented on app/src/main/java/com/pindex/main/ui/activities/AugmentedRealityActivity.kt
> +    private lateinit var help : ImageView
`help` is not a really meaningful name, maybe something like `helpButton` would be better

2021-05-05 14:18 UTC, lucasrlt commented on app/src/main/java/com/pindex/main/ui/activities/AugmentedRealityActivity.kt
> +            val intent = Intent(this,ARHelpActivity::class.java)
A formatter run on that file too would be good

2021-05-05 14:18 UTC, lucasrlt commented on app/src/main/res/layout/activity_ar_help.xml
> +            android:paddingTop="20sp"
Some paddings could be moved to the dimensions file here since they are reused quite a lot, same for the height (applicable to the entire file)

2021-05-06 01:20 UTC, lucasrlt approved these changes
Everything looks good to me after the changes, gj !

2021-05-06 10:29 UTC, amomo25 approved these changes
The code is clean and well documented, and the design is pretty nice. Great job !

2021-05-06 10:32 UTC, merged