Pxs 943 optimize tours
pindex/android pull request #352
Opened 2021-07-04 17:10 UTC by ToufiPF

Optimize a bit MapboxActivity:
- Limit framerate to 30 fps
- Open POIs in a dedicated Activity => Mapbox activity is stopped automatically when a POI is displayed.
- Remove useless queryFeature in onMapClick (can work with Tour's POIs directly)

Design changes: POI is now displayed in an activity 
- I've got hesitations about the style, which is better ? 

|   White band on top <br/>(with a bit more of margin below the exit button?)   |    Exit button hovers on top of content    |
| ----------------------------- | ------------------------------------------------- |
| <img src="https://user-images.githubusercontent.com/13187080/124393311-2116a900-dcfa-11eb-8661-6880469d0909.png" width="300" /> | <img src="https://user-images.githubusercontent.com/13187080/124393402-a306d200-dcfa-11eb-855e-3810443cc6ec.png" width="300" />  |

- Do I keep the shadow for the exit button ?

2021-07-04 17:24 UTC, timotheeduran commented
Option 2 (Exit button hovers on top of content) is better.

2021-07-04 17:24 UTC, timotheeduran commented
You can keep the shadow.

2021-07-05 07:41 UTC, qtipee requested changes

2021-07-05 07:41 UTC, qtipee commented on app/src/main/java/com/pindex/main/ui/activities/MapboxActivity.kt
> +                    println("ON MAP CLICK : distance $dist")
Remove `println` ?

2021-07-05 07:41 UTC, qtipee commented on app/src/main/java/com/pindex/main/ui/activities/MapboxActivity.kt
> +            println("ON MAP CLICK : point $point ; ${tourDto.points?.size}")
Remove `println` ?

2021-07-05 07:41 UTC, qtipee commented on app/src/main/java/com/pindex/main/ui/activities/MapboxActivity.kt
> +            println("ON MAP CLICK : poi $poi")
Remove `println` ?

2021-07-05 07:41 UTC, qtipee commented on app/src/main/java/com/pindex/main/ui/activities/MapboxActivity.kt
> +        mapboxView.setMaximumFps(30)
Can we use a constant here instead of a magic number ?

2021-07-05 07:47 UTC, ToufiPF commented on app/src/main/java/com/pindex/main/ui/activities/MapboxActivity.kt
> +                    println("ON MAP CLICK : distance $dist")
Yep done in the last commit

2021-07-05 07:47 UTC, ToufiPF commented on app/src/main/java/com/pindex/main/ui/activities/MapboxActivity.kt
> +        mapboxView.setMaximumFps(30)
I'm on it

2021-07-05 10:06 UTC, qtipee approved these changes

2021-07-05 19:03 UTC, merged