PXS-545 Create view title block
pindex/android pull request #7
Opened 2021-02-02 10:28 UTC by qtipee

Create a view component that extends the default TextView with the BigHeader styles.

This PR also adds a simple tour activity that is displayed when touching a tour in the RecyclerView.

2021-02-02 20:46 UTC, timotheeduran requested changes
Looking super great! Just a few details to change.

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/ui/blocks/BigHeader.kt
> +    init {
Missing clear documentation. Use [Kotlin style guide on documentation comments](Invitation for a short virtual coffee) for more information.

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/ui/blocks/BigHeader.kt
> +        setTextColor(Color.BLACK)
Our default color isn't black, but a color called _Pindex Lead_, which is represented by _HEX #212121_. UI guidelines are coming.

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/ui/blocks/BigHeader.kt
> +        typeface = ResourcesCompat.getFont(context, R.font.montserrat_bold)
_BigHeader_ uses Montserrat **ExtraBold** and not Bold.

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/ui/blocks/BigHeader.kt
> +        typeface = ResourcesCompat.getFont(context, R.font.montserrat_bold)
By looking at the screenshot you did, it visually seems to be the right font, however...  Can you double-check? Here is the model:

![bigHeader](https://user-images.githubusercontent.com/26303997/106657850-cfc48b00-659c-11eb-9ace-7d29c0eccb2b.png)

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/home/TourActivity.kt
> +class TourActivity : AppCompatActivity() {
I would not use the term _Tour_ in this case, as this _Activity_ will also be used to display Pindex Events and Pindex Activities from the Pindex Flow database and not only Pindex Tours. On iOS, we use the term `Activity`, but it would clearly cause some confusion here with the term `Activity` from the Android SDK.

What about `Experience`? A Tour, Activity, or Event is an experience. This would give `ExperienceActivity`.

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/home/TourActivity.kt
> +        if (title?.isBlank()!!) {
I'm not an expert in the Android SDK life cycle, but on iOS is generally safer to set both `visibility` and `text` in both cases of the condition. Based on previous experience, we sometimes get the case where things get cached and if the visibility was previously `View.GONE` but now should be displayed, it might happen that we never actually change the visibility. But again, not an expert with Android.

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/home/ItemAdapter.kt
> +    var onItemClick: ((String) -> Unit)? = null
I would use a multiline comment. https://kotlinlang.org/docs/reference/coding-conventions.html#documentation-comments

2021-02-02 20:46 UTC, timotheeduran commented on app/src/main/java/com/pindex/main/home/HomeActivity.kt
>  import androidx.appcompat.app.AppCompatActivity
Doesn't follow alphabetical order.

2021-02-03 09:38 UTC, qtipee commented on app/src/main/java/com/pindex/main/home/TourActivity.kt
> +class TourActivity : AppCompatActivity() {
I really like the word `Experience` hehe

2021-02-03 09:44 UTC, qtipee commented on app/src/main/java/com/pindex/main/home/TourActivity.kt
> +        if (title?.isBlank()!!) {
Can't tell as I am not an Android expert yet, but I guess we don't have anything to lose by doing so.

2021-02-03 10:19 UTC, timotheeduran approved these changes

2021-02-03 10:20 UTC, merged